#!/usr/bin/env python3

import argparse
import os
import subprocess
import time

config = {
  "log_dir": "/tmp/disk_monitor",
  "dirs_to_check": ["/"],
  "file_categories": {
    "ignored": [
      "/var/lib/rsyslog/imjournal.state"
    ]
  },
  "dir_categories": {
    "ignored": [
      # These directories are ignored because they can cause permissions issues
      "/mnt",
      # These directories are ignored because they're very large, and typically irrelevant
      "/proc",            # ~611k
      "/sys",             # ~106k
      "/var/lib/docker",  # ~1.2m
      # These directories are ignored because they're cluttery
      "/root/.vscode-server",
      "/run/docker/runtime-runc",
      "/run/log/journal"
    ],
    "unimportant": [
      "/dev",
      "/run",
      "/usr/lib/.build-id",
      "/var/cache",
      "/var/run"
    ],
    "notable": [
      "/lib",
      "/usr/include",
      "/usr/lib",
      "/usr/share",
      "/usr/src"
    ],
    "key": [
      "/usr/local",
      "/var",
      "/root",
      "/home",
      "/opt",
      "/etc",
      "/bin",
      "/sbin",
      "/usr/bin",
      "/usr/sbin",
      "/usr/local/bin",
      "/usr/local/sbin",
      "/usr/lib/systemd/system",
    ]
  }
}

system = {
  "start_time": float,
  "end_time": float,
  "log_path": str,
  "get_files_first_call": True,
  "files_examined_count": int,
  "uncategorized_files": {
    "born": [],
    "modified": [],
    "changed": [],
    "accessed": []
  },
  "categorized_files": {
    "logs": {
      "born": [],
      "modified": [],
      "changed": [],
      "accessed": []
    },
    "ignored": {
      "born": [],
      "modified": [],
      "changed": [],
      "accessed": []
    },
    "unimportant": {
      "born": [],
      "modified": [],
      "changed": [],
      "accessed": []
    },
    "notable": {
      "born": [],
      "modified": [],
      "changed": [],
      "accessed": []
    },
    "key": {
      "born": [],
      "modified": [],
      "changed": [],
      "accessed": []
    }
  }
}


def start():
  system["start_time"] = time.time()
  handle_args()
  handle_logs()

  print()   # I like formatting, dont judge me
  manual_trigger = system["args"].command[0] == "man" or system["args"].command[0] == "manual"
  if manual_trigger:
    input("Press enter when ready to scan...")
    system["end_time"] = time.time()
  else:
    execute_subprocess()

  set_uncategorized_files()
  categorize_uncategorized_files()
  output_categorized_files()
  output_stats()


def handle_args():
  parser = argparse.ArgumentParser(
    description="Show disk changes caused by an operation."
  )
  parser.add_argument(
    "command",
    type=str,
    nargs='+',
    help='Command to execute. Alternatively, keyword "manual"'
  )
  parser.add_argument(
    "-b", "--no-born",
    action="store_true",
    help="Toggles including files born during the operation.\nDefault On."
  )
  parser.add_argument(
    "-m", "--no-modified",
    action="store_true",
    help="Toggles including files modified during the operation.\nDefault On."
  )
  parser.add_argument(
    "-c", "--no-changed",
    action="store_true",
    help="Toggles including files changed during the operation.\nDefault Off."
  )
  parser.add_argument(
    "-a", "--no-accessed",
    action="store_true",
    help="Toggles including files accessed during the operation.\nDefault Off."
  )
  args = parser.parse_args()

  system["args"] = args


def handle_logs():
  make_log_dir()
  set_log_path()


def make_log_dir():
  log_dir = config["log_dir"]
  os.makedirs(log_dir, exist_ok=True)


def set_log_path():
  command_as_filename = get_command_as_filename()
  if command_as_filename:
    set_log_path_using_command(command_as_filename)
  else:
    set_log_path_using_time()


def get_command_as_filename():
  command = system["args"].command
  command_as_string = ' '.join(command)
  command_as_filename = command_as_string.lower().replace(" ", "_").replace("/", "_")

  return command_as_filename


def set_log_path_using_command(command_as_filename):
  LOG_PATH = os.path.join(
    config["log_dir"],
    f"{command_as_filename}.log"
  )
  system["log_path"] = LOG_PATH


def set_log_path_using_time():
  current_time = time.time()
  log_path = os.path.join(
    config["log_dir"],
    f"manual-{current_time}.log"
  )
  system["log_path"] = log_path


def execute_subprocess():
  command = system["args"].command
  try:
    subprocess.run(command, check=True)
  except subprocess.CalledProcessError as e:
    red = "\033[38;5;160m"
    white = "\033[0m"
    print(f"\n{red}Subprocess failed with exit code:{white} {e.returncode}\n")
  system["end_time"] = time.time()


def set_uncategorized_files():
  dirs_to_check = config["dirs_to_check"]
  file_paths = get_files_except_ignored(dirs_to_check)
  uncategorized_files = get_file_paths_touched_after_start(file_paths)
  system["uncategorized_files"] = uncategorized_files


def categorize_uncategorized_files():
  output_num_of_uncategorized_files()
  set_ignored_files()
  set_key_files()
  set_log_files()
  set_notable_files()
  set_unimportant_files()


def output_categorized_files():
  any_ignored_files = (
    len(system["categorized_files"]["ignored"]["born"])
    + len(system["categorized_files"]["ignored"]["modified"])
    + len(system["categorized_files"]["ignored"]["changed"])
    + len(system["categorized_files"]["ignored"]["accessed"])
  ) > 0
  any_unimportant_files = (
    len(system["categorized_files"]["unimportant"]["born"])
    + len(system["categorized_files"]["unimportant"]["modified"])
    + len(system["categorized_files"]["unimportant"]["changed"])
    + len(system["categorized_files"]["unimportant"]["accessed"])
  ) > 0
  any_notable_files = (
    len(system["categorized_files"]["notable"]["born"])
    + len(system["categorized_files"]["notable"]["modified"])
    + len(system["categorized_files"]["notable"]["changed"])
    + len(system["categorized_files"]["notable"]["accessed"])
  ) > 0
  any_key_files = (
    len(system["categorized_files"]["key"]["born"])
    + len(system["categorized_files"]["key"]["modified"])
    + len(system["categorized_files"]["key"]["changed"])
    + len(system["categorized_files"]["key"]["accessed"])
  ) > 0
  any_log_files = (
    len(system["categorized_files"]["logs"]["born"])
    + len(system["categorized_files"]["logs"]["modified"])
    + len(system["categorized_files"]["logs"]["changed"])
    + len(system["categorized_files"]["logs"]["accessed"])
  ) > 0
  any_uncategorized_files = (
  len(system["uncategorized_files"]["born"])
  + len(system["uncategorized_files"]["modified"])
  + len(system["uncategorized_files"]["changed"])
  + len(system["uncategorized_files"]["accessed"])
  ) > 0

  truncate_file(system["log_path"])

  if any_ignored_files:
    output_ignored_files()
  if any_unimportant_files:
    output_unimportant_files()
  if any_notable_files:
    output_notable_files()
  if any_key_files:
    output_key_files()
  if any_log_files:
    output_log_files()
  if any_uncategorized_files:
    output_uncategorized_files()
  print()


def output_stats():
  print()

  files_examined_count = system["files_examined_count"]
  print(f"Examined files: {files_examined_count}")


def get_files_except_ignored(dirs):
  first_call = system["get_files_first_call"]
  system["get_files_first_call"] = False

  if first_call:
    print(f"Checking directories:\n{dirs}\n...")

  file_paths = []
  for directory in dirs:
    for file_name in os.listdir(directory):
      file_path = os.path.join(directory, file_name)
      if os.path.islink(file_path):
        pass # Ignore symlinks
      elif os.path.isdir(file_path):
        if file_path not in config["dir_categories"]["ignored"]:
          file_paths.extend(get_files_except_ignored([file_path]))
      elif os.path.isfile(file_path):
        file_paths.append(file_path)

  if first_call:
    system["files_examined_count"] = f"{len(file_paths):,}"

  return file_paths


def get_file_paths_touched_after_start(file_paths):
  start_time = system["start_time"]
  end_time = system["end_time"]
  ignored_files = config["file_categories"]["ignored"]

  files_touched = {
    "born": [],
    "modified": [],
    "changed": [],
    "accessed": []
  }
  processed = []

  for file_path in file_paths:
    if os.path.exists(file_path):
      stat = os.stat(file_path)
      birth_time = stat.st_ctime
      modify_time = stat.st_mtime
      change_time = stat.st_ctime
      access_time = stat.st_atime

      if file_path not in ignored_files:
        if (
          not system["args"].no_born
          and birth_time > start_time
          and birth_time < end_time
        ):
          files_touched["born"].append(file_path)
          processed.append(file_path)
        if (
          not system["args"].no_modified
          and modify_time > start_time
          and modify_time < end_time
          and file_path not in processed
        ):
          files_touched["modified"].append(file_path)
          processed.append(file_path)
        if (
          not system["args"].no_changed
          and change_time > start_time
          and modify_time < end_time
          and file_path not in processed
        ):
          files_touched["changed"].append(file_path)
          processed.append(file_path)
        if (
          not system["args"].no_accessed
          and access_time > start_time
          and modify_time < end_time
          and file_path not in processed
        ):
          files_touched["accessed"].append(file_path)
          processed.append(file_path)

  return files_touched


def output_num_of_uncategorized_files():
  born_file_count = len(system["uncategorized_files"]["born"])
  modified_file_count = len(system["uncategorized_files"]["modified"])
  changed_file_count = len(system["uncategorized_files"]["changed"])
  accessed_file_count = len(system["uncategorized_files"]["accessed"])
  files_to_categorize = (
    born_file_count
    + modified_file_count
    + changed_file_count
    + accessed_file_count
  )
  files_to_categorize_formatted = f"{files_to_categorize:,}"

  print(f"\nCategorizing files: {files_to_categorize_formatted}...")


def set_log_files():
  set_born_log_files()
  set_modified_log_files()
  set_changed_log_files()
  set_accessed_log_files()


def set_ignored_files():
  set_born_ignored_files()
  set_modified_ignored_files()
  set_changed_ignored_files()
  set_accessed_ignored_files()


def set_born_ignored_files():
  ignored_born_files = system["categorized_files"]["ignored"]["born"]
  ignored_dirs = config["dir_categories"]["ignored"]
  set_some_born_files(ignored_born_files, ignored_dirs)


def set_modified_ignored_files():
  ignored_modified_files = system["categorized_files"]["ignored"]["modified"]
  ignored_dirs = config["dir_categories"]["ignored"]
  set_some_modified_files(ignored_modified_files, ignored_dirs)


def set_changed_ignored_files():
  ignored_changed_files = system["categorized_files"]["ignored"]["changed"]
  ignored_dirs = config["dir_categories"]["ignored"]
  set_some_changed_files(ignored_changed_files, ignored_dirs)


def set_accessed_ignored_files():
  ignored_accessed_files = system["categorized_files"]["ignored"]["accessed"]
  ignored_dirs = config["dir_categories"]["ignored"]
  set_some_accessed_files(ignored_accessed_files, ignored_dirs)


def set_unimportant_files():
  set_born_unimportant_files()
  set_modified_unimportant_files()
  set_changed_unimportant_files()
  set_accessed_unimportant_files()


def set_born_unimportant_files():
  unimportant_born_files = system["categorized_files"]["unimportant"]["born"]
  unimportant_dirs = config["dir_categories"]["unimportant"]
  set_some_born_files(unimportant_born_files, unimportant_dirs)


def set_modified_unimportant_files():
  unimportant_modified_files = system["categorized_files"]["unimportant"]["modified"]
  unimportant_dirs = config["dir_categories"]["unimportant"]
  set_some_modified_files(unimportant_modified_files, unimportant_dirs)


def set_changed_unimportant_files():
  unimportant_changed_files = system["categorized_files"]["unimportant"]["changed"]
  unimportant_dirs = config["dir_categories"]["unimportant"]
  set_some_changed_files(unimportant_changed_files, unimportant_dirs)


def set_accessed_unimportant_files():
  unimportant_accessed_files = system["categorized_files"]["unimportant"]["accessed"]
  unimportant_dirs = config["dir_categories"]["unimportant"]
  set_some_accessed_files(unimportant_accessed_files, unimportant_dirs)


def set_born_log_files():
  uncategorized_born_files = system["uncategorized_files"]["born"]
  born_logs = system["categorized_files"]["logs"]["born"]
  for file_path in uncategorized_born_files.copy():
    if is_log_file(file_path):
      born_logs.append(file_path)
      uncategorized_born_files.remove(file_path)


def set_modified_log_files():
  uncategorized_modified_files = system["uncategorized_files"]["modified"]
  modified_logs = system["categorized_files"]["logs"]["modified"]
  for file_path in uncategorized_modified_files.copy():
    if is_log_file(file_path):
      modified_logs.append(file_path)
      uncategorized_modified_files.remove(file_path)

def set_changed_log_files():
  uncategorized_changed_files = system["uncategorized_files"]["changed"]
  changed_logs = system["categorized_files"]["logs"]["changed"]
  for file_path in uncategorized_changed_files.copy():
    if is_log_file(file_path):
      changed_logs.append(file_path)
      uncategorized_changed_files.remove(file_path)

def set_accessed_log_files():
  uncategorized_accessed_files = system["uncategorized_files"]["accessed"]
  accessed_logs = system["categorized_files"]["logs"]["accessed"]
  for file_path in uncategorized_accessed_files.copy():
    if is_log_file(file_path):
      accessed_logs.append(file_path)
      uncategorized_accessed_files.remove(file_path)


def set_notable_files():
  set_born_notable_files()
  set_modified_notable_files()
  set_changed_notable_files()
  set_accessed_notable_files()


def set_born_notable_files():
  notable_born_files = system["categorized_files"]["notable"]["born"]
  notable_dirs = config["dir_categories"]["notable"]
  set_some_born_files(notable_born_files, notable_dirs)


def set_modified_notable_files():
  notable_modified_files = system["categorized_files"]["notable"]["modified"]
  notable_dirs = config["dir_categories"]["notable"]
  set_some_modified_files(notable_modified_files, notable_dirs)


def set_changed_notable_files():
  notable_changed_files = system["categorized_files"]["notable"]["changed"]
  notable_dirs = config["dir_categories"]["notable"]
  set_some_changed_files(notable_changed_files, notable_dirs)


def set_accessed_notable_files():
  notable_accessed_files = system["categorized_files"]["notable"]["accessed"]
  notable_dirs = config["dir_categories"]["notable"]
  set_some_accessed_files(notable_accessed_files, notable_dirs)


def set_key_files():
  set_born_key_files()
  set_modified_key_files()
  set_changed_key_files()
  set_accessed_key_files()


def set_born_key_files():
  key_born_files = system["categorized_files"]["key"]["born"]
  key_dirs = config["dir_categories"]["key"]
  set_some_born_files(key_born_files, key_dirs)


def set_modified_key_files():
  key_modified_files = system["categorized_files"]["key"]["modified"]
  key_dirs = config["dir_categories"]["key"]
  set_some_modified_files(key_modified_files, key_dirs)


def set_changed_key_files():
  key_changed_files = system["categorized_files"]["key"]["changed"]
  key_dirs = config["dir_categories"]["key"]
  set_some_changed_files(key_changed_files, key_dirs)


def set_accessed_key_files():
  key_accessed_files = system["categorized_files"]["key"]["accessed"]
  key_dirs = config["dir_categories"]["key"]
  set_some_accessed_files(key_accessed_files, key_dirs)


def set_some_born_files(some_born_files, some_criteria_dirs):
  uncategorized_born_files = system["uncategorized_files"]["born"]
  set_some_files(uncategorized_born_files, some_born_files, some_criteria_dirs)


def set_some_modified_files(some_modified_files, some_criteria_dirs):
  uncategorized_modified_files = system["uncategorized_files"]["modified"]
  set_some_files(uncategorized_modified_files, some_modified_files, some_criteria_dirs)


def set_some_changed_files(some_changed_files, some_criteria_dirs):
  uncategorized_changed_files = system["uncategorized_files"]["changed"]
  set_some_files(uncategorized_changed_files, some_changed_files, some_criteria_dirs)


def set_some_accessed_files(some_accessed_files, some_criteria_dirs):
  uncategorized_accessed_files = system["uncategorized_files"]["accessed"]
  set_some_files(uncategorized_accessed_files, some_accessed_files, some_criteria_dirs)


def set_some_files(some_uncategorized_files, some_files, some_criteria_dirs):
  for directory in some_criteria_dirs:
    for file_path in some_uncategorized_files.copy():
      is_some_file = is_file_of_directory(file_path, directory)
      if is_some_file:
        some_files.append(file_path)
        # TODO: This throws sometimes, not sure why
        # try:
        some_uncategorized_files.remove(file_path)
        # except ValueError:
        #   pass


def output_ignored_files():
  tag = "Ignored"
  grey = "\033[38;5;242m"
  ignored_categorized_files = system["categorized_files"]["ignored"]
  output_some_files(tag, ignored_categorized_files, grey)


def output_unimportant_files():
  tag = "Unimportant"
  red = "\033[38;5;160m"
  unimportant_categorized_files = system["categorized_files"]["unimportant"]
  output_some_files(tag, unimportant_categorized_files, red)


def output_notable_files():
  tag = "Notable"
  yellow = "\033[38;5;190m"
  notable_categorized_files = system["categorized_files"]["notable"]
  output_some_files(tag, notable_categorized_files, yellow)


def output_key_files():
  tag = "Key"
  green = "\033[38;5;46m"
  key_categorized_files = system["categorized_files"]["key"]
  output_some_files(tag, key_categorized_files, green)


def output_log_files():
  tag = "Logs"
  blue = "\033[38;5;39m"
  log_files = system["categorized_files"]["logs"]
  output_some_files(tag, log_files, blue)


def output_uncategorized_files():
  tag = "Uncategorized"
  white = "\033[0m"
  uncategorized_categorized_files = system["uncategorized_files"]
  output_some_files(tag, uncategorized_categorized_files, white)


def output_some_files(tag, some_categorized_files, color):
  print(f"\n{tag}:")

  append_to_file(system["log_path"], f"\n_____{tag}_____")
  output_some_born_files(some_categorized_files["born"], color)
  output_some_modified_files(some_categorized_files["modified"], color)
  output_some_changed_files(some_categorized_files["changed"], color)
  output_some_accessed_files(some_categorized_files["accessed"], color)


def output_some_born_files(some_categorized_born_files, color):
  white = "\033[0m"
  for file_path in some_categorized_born_files:
    print(f"      Born: {color}{file_path}{white}")
    append_to_file(system["log_path"], f"      Born: {file_path}")


def output_some_modified_files(some_categorized_modified_files, color):
  white = "\033[0m"
  for file_path in some_categorized_modified_files:
    print(f"  Modified: {color}{file_path}{white}")
    append_to_file(system["log_path"], f"  Modified: {file_path}")


def output_some_changed_files(some_categorized_changed_files, color):
  white = "\033[0m"
  for file_path in some_categorized_changed_files:
    print(f"   Changed: {color}{file_path}{white}")
    append_to_file(system["log_path"], f"   Changed: {file_path}")


def output_some_accessed_files(some_categorized_accessed_files, color):
  white = "\033[0m"
  for file_path in some_categorized_accessed_files:
    print(f"  Accessed: {color}{file_path}{white}")
    append_to_file(system["log_path"], f"  Accessed: {file_path}")


def truncate_file(file_path):
  with open(file_path, "w", encoding="utf-8"):
    pass


def append_to_file(file_path, content):
  with open(file_path, "a", encoding="utf-8") as f:
    f.write(f"{content}\n")


def is_subdirectory(potential_sub_dir, dir2):
  dir2_length = len(dir2)
  potential_sub_dir_root = potential_sub_dir[:dir2_length]

  return potential_sub_dir_root == dir2


def is_file_of_directory(file_path, directory):
  is_direct_file_of_dir = os.path.dirname(file_path) == directory
  is_indirect_file_of_dir = is_subdirectory(os.path.dirname(file_path), directory)
  if is_direct_file_of_dir or is_indirect_file_of_dir:
    return True
  else:
    return False


def is_log_file(file_path):
  directory = os.path.dirname(file_path)
  file_name = os.path.basename(file_path)
  return (
    "logs" in directory
    or (
      "log" in file_name
      and "login" not in file_name
    )
  )


start()

