log_dir: "./logs"
dirs_to_check:
  - "/"
file_categories:
  ignored: []
dir_categories:
  ignored: []
  unimportant:
    - "/Users\\gmukko\\AppData\\Local\\Python\\pythoncore-3.14-64\\"
  notable: []
  key: []
